---
title: "Data preparation with EDGEtransport"
author: "Marianna Rottoli"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data preparation with EDGEtransport}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Description

The input data preparation routine of EDGE-Transport produces transport detailed data compatible with the structure of REMIND. The code is provided as R package, while the input data is available upon request. The input data is necessary to run the package. The input data generation routine uses the functions provided in the [edgeTrpLib](https://github.com/pik-piam/edgeTrpLib) package.

## Usage

The package can be installed from github...

Data can be generated as follows:

`
generateEDGEdata(input_folder, output_folder, SSP_scen = "SSP2", techscen = NULL, IEAbal = NULL, GDP_country = NULL, POP_country = NULL, trsp_incent = NULL, RatioPPP2MER_country = NULL, JRC_IDEES_Trsp = NULL, JRC_IDEES_MarBunk = NULL, storeRDS = FALSE)
`

Where:

`input_folder` character string containing the path to the input data folder

`output_folder` character string containing the path where output data are saved

`SSP_scen` character string containing the selected SSP scenario. Options are: `SDP`, `SSP1`, `SSP2`, `SSP2-Ariadne`, `SSP2_LowEn`, `SSP5`. By default, `SSP2` is selected

`techscen` character string containing the EDGE-T technology scenario, if provided. By default, SSP/SDP "coherent" technology development is selected. Hybrid matches SSP-technology scenario (e.g. SSP2 with high hydrogen demand) are allowed.

`IEAbal` use mrremind generated data: in case of a REMIND preprocessing run, load population.  Product of: `calcOutput("IO", subtype = "IEA_output", aggregate = TRUE)`

`GDP_country` use mrremind generated data: in case of a REMIND preprocessing run, load GDP.  Product of: `calcOutput("GDPppp", aggregate =F)`

`RatioPPP2MER_country use` mrremind generated data: in case of a REMIND preprocessing run, load ratio between PPP and MER GDP.  Product of: `calcOutput("RatioPPP2MER", aggregate =F)`

`POP_country` use mrremind generated data: in case of a REMIND preprocessing run, load IEA balances. Product of: `calcOutput("Population", aggregate =F)`

`JRC_IDEES_Trsp` use mrremind generated data: in case of a REMIND preprocessing run, load JRC_IDEE data. Product of: `calcOutput("JRC_IDEES", subtype="Transport")`

`JRC_IDEES_MarBunk` use mmrremind generated data: in case of a REMIND preprocessing run, load JRC_IDEE data. Product of: `calcOutput("JRC_IDEES", subtype="maritimeBunkers")`

`trsp_incent` use mmrremind generated data: in case of a REMIND preprocessing run, load transportSubsidies data. Product of: `readSource("TransportSubsidies", convert=T)`

`storeRDS` logical. If `TRUE`, levels 0, 1 and 2 temporary output RDS files are saved, and a reporting PDF to validate the data is produced in level_2. By default, the parameter is set to `FALSE`.


## Data generation structure

The package contains three levels of data wrangling.

* Level 0: this level performs the raw data loading and processing. The scripts in this level load the input data, such as: detailed historical demand, technology performances-load factor, intensity, value of time, inconvenience costs for 4wheelers.
* Level 1: in this level the inconvenience costs and preference factors are calibrated on the historical transport demand. The calibrated preferences are then projected in time for technologies-vehicles-modes based on assumptions of the evolution of the transport system.
* Level 2: the future composition of the transport system is defined via a logit function. The total demand for transport is calculated via regressions. Data is then saved in the form of .csv files.

## Scenarios description

The data preparation routine allows to provide combinations of transport scenarios and macro-economic scenarios. The transport scenarios are characterized by a set of assumptions about technological development, evolution of preferences for technologies and transport modes, lifestyle changes, introduction of policy packages. The assumptions are reported in a set of switches reported in the mapping file `EDGEtransport/data-raw/EDGEscenario_description.csv`. An extensive description of the scenarios is provided here [CIT]. The scenario options are the following:

`ConvCase` stands for *Conventional Case*, represents a conventional case, internal combustion engines, no incentives to BEVs and FCEVs

`ElecEra` stands for *Electric Era* incentives to BEVs, takeover of alternative vehicles at the expenses of conventional vehicles

`ElecEraWise` stands for *Electric Era* with also *sustainable demand* projections and lifestyle changes concerning: a moderate growth of demand, an increased preference for public transport and non-motorized modes.

`HydrHype` stands for *Hydrogen Hype* incentives to FCEVs, slow development of BEVs, takeover of alternative vehicles at the expenses of conventional vehicles

The macro-economic scenarios are based on the Shared Socio-Economic Pathways [see @riahi_shared_2017]. The entries that vary across scenarios are GDP and population projections. There are no assumptions specific to transport structure across the various SSPs.

## References
