---
title: "Edge Transport Compare Scenarios"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
    toc: yes
    number_sections: yes
    toc_depth: 6
    keep_tex: false
    template: cs2_latex_template.tex
    includes: 
      in_header: cs_pdf_header_include.tex
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 6
    number_sections: yes
geometry: "a4paper,landscape,left = 0.5cm,right = 0.5cm,top = 0.5cm,bottom = 0.5cm,footnotesep=0.0cm,footskip = 0.1cm"
params:
  mifScen: ""
  mifScenNames: !r c()
  mifHist: ""
  yearsScen: !r c(seq(2005, 2060, 5), seq(2070, 2100, 10))
  yearsHist: !r c(seq(2010, 2020, 1), seq(2025, 2100, 5))
  yearsBarPlot: !r c(2010, 2030, 2050, 2100)
  reg: !r c("OAS","MEA","SSA","LAM","REF","CAZ","CHA","IND","JPN","USA","NEU","EUR","World")
  modelsHistExclude: !r c()
  sections: !r c("01_energy_demand","02_energy_services","03_energy_intensity", "04_stock_and_sales", "05_Emissions", "06_costs_and_shareweight_trends")
  userSectionPath: null
  mainReg: "World"
  figWidth: 15 
  figHeight: 10
  warning: no
subparagraph: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  warning = params$warning,
  fig.width = params$figWidth, 
  fig.height = params$figHeight)
```


```{r libraries, include=FALSE}
# kableExtra must not be loaded before the call of library(kableExtra) below,
# as its .onLoad() function must be called to tell knitr about add necessary
# LaTeX libraries needed for tables.
# If the following line is not included, successive calls to compareScenarios2()
# may cause "Undefined control sequence" errors in LaTeX.
try(unloadNamespace("kableExtra"), silent = TRUE)

library(gridExtra)
options(tidyverse.quiet = TRUE)
library(tidyverse)
library(kableExtra)
library(devtools)
library(mip)
library(quitte)
library(edgeTransport)
library(data.table)
```

```{r read scenario mifs}
# Read *.mif-files as nested tibble.
tibble(path = unname(params$mifScen)) %>%
  rowid_to_column("fileid") %>%
  mutate(data = map(
    path,
    read.quitte,
    factors = TRUE,
    # read.quitte() default NA-strings and Inf, -Inf
    na.strings = c("UNDF", "NA", "N/A", "n_a", "Inf", "-Inf"))) %>%
  unnest(data) %>%
  nest(data = -c(fileid, path, scenario)) ->
  dataScenNested
# Add column character column "newScenarioName",
# either with contents of params$mifScenNames or copy names from column scenario.
if (is.null(params$mifScenNames)) {
  dataScenNested %>%
    mutate(newScenarioName = as.character(scenario)) ->
    dataScenNested
} else {
  dataScenNested %>%
    left_join(
      tibble(
        fileid = seq_along(params$mifScen),
        newScenarioName = params$mifScenNames),
      by = "fileid") ->
    dataScenNested
}
# Check for duplicated scenario names.
if (anyDuplicated(dataScenNested$newScenarioName)) {
  warning("There are duplicated scenario names. They will be renamed.")
  dataScenNested %>%
    mutate(newScenarioName = make.unique(newScenarioName)) ->
    dataScenNested
}
# Retrieve data for reference table to be shown at the beginning of the document.
dataScenNested %>%
  select(fileid, path, scenario, newScenarioName) ->
  fileReference
# Apply renaming of scenario, unnest, and select only relevant columns.
dataScenNested %>%
  mutate(scenario = factor(newScenarioName, levels = newScenarioName)) %>%
  unnest(data) %>%
  select(model, scenario, region, variable, unit, period, value) ->
  dataScen
```

```{r define scenario colors}
# Get colors of scenarios to be used, e.g., in the info sections.
# They will coincide with the colors of the scenarios in line plots.
scenarioColors <- plotstyle(fileReference$newScenarioName)
lightenColor <- function(clr, by) {
  colRGB <- colorRamp(c(clr, "white"))(by)
  rgb(colRGB[1], colRGB[2], colRGB[3], maxColorValue = 255)
}
bkgndColors <- sapply(scenarioColors, lightenColor, by = 0.5)
```


```{r read historical mif}
params$mifHist %>%
  read.quitte(factors = TRUE) ->
  dataHist
```


```{r preprocess}
# Filter years and NA.
dataScen %>%
  filter(period %in% params$yearsScen) ->
  dataScen
dataHist %>%
  filter(period %in% params$yearsHist, !(model %in% params$modelsHistExclude), !is.na(value)) %>%
  droplevels() ->
  dataHist
# Combine into one data frame and remove old.
data <- bind_rows(dataScen, dataHist)
rm(dataScen, dataScenNested, dataHist)
# In the variable names, replace |+|, |++|, |+++|, ... by |.
data %>%
  mutate(
    varplus = as.character(variable),
    variable = remind2::deletePlus(variable)) ->
  data
# Filter regions.
if (!is.null(params$reg)) {
  data %>%
    filter(region %in% params$reg) ->
    data
}
```


```{r Corrections}
# TODO: Should not be done in compareScenarios.
# Change unit million US$2005/yr to billion US$2005/yr.
# Relevant for ARIADNE historical EUR GDP|PPP.
bind_rows(
  data %>% filter(!unit %in% c("million US$2005/yr")),
  data %>%
    filter(unit == "million US$2005/yr") %>%
    mutate(
      unit = "billion US$2005/yr",
      value = value / 1000)) ->
  data
```


```{r reference models for historical}
# Sometimes it is necessary to choose a single model for the historical data,
# e.g., calculating per capita variables. These reference models are defined here.
histRefModel <- c(
  "Population" = "WDI",
  "GDP|PPP pCap" = "James_IMF")
```


```{r calcuate pCap variables}
# For all variables in following table, add a new variable to data with the name
# "OldName pCap". Calculate its value by
#     OldValue * conversionFactor 
# and set its unit to newUnit. 
# The new variable "OldName pCap" will be available in the plot sections.
pCapVariables <- tribble(
  ~variable, ~newUnit, ~conversionFactor,
  "GDP|PPP", "kUS$2005", 1e6,
  "ES|Transport|Pass", "pkm/yr", 1e9,
  "ES|Transport|Pass|Aviation", "pkm/yr", 1e9,
  "ES|Transport|Bunkers|Pass|International Aviation", "pkm/yr", 1e9,
  "ES|Transport|Pass|Domestic Aviation", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|Bus", "pkm/yr", 1e9,
  "ES|Transport|Pass|Non-motorized|Walk", "pkm/yr", 1e9,
  "ES|Transport|Pass|Non-motorized|Cycle", "pkm/yr", 1e9,
  "ES|Transport|Pass|Rail|non-HSR", "pkm/yr", 1e9,
  "ES|Transport|Pass|Rail|HSR", "pkm/yr", 1e9,
  "ES|Transport|Freight", "tkm/yr", 1e9,
  "ES|Transport|Bunkers|Freight|International Shipping", "tkm/yr", 1e9,
  "ES|Transport|Freight|Road", "tkm/yr", 1e9,
  "ES|Transport|Freight|Domestic Shipping", "tkm/yr", 1e9,
  "ES|Transport|Freight|Rail", "tkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Four Wheelers", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Two Wheelers", "pkm/yr", 1e9,
  "ES|Transport|Pass|non-LDV", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|BEV", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|FCEV", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Gases", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Hybrid electric", "pkm/yr", 1e9,
  "ES|Transport|Pass|Road|LDV|Liquids", "pkm/yr", 1e9,
  "ES|Transport|Freight with bunkers", "tkm/yr", 1e9,
  "ES|Transport|Freight|Road|Electric", "pkm/yr", 1e9,
  "ES|Transport|Freight|Road|FCEV", "pkm/yr", 1e9,
  "ES|Transport|Freight|Road|Gases", "pkm/yr", 1e9,
  "ES|Transport|Freight|Road|Liquids", "pkm/yr", 1e9)

data %>% 
  filter(variable == "Population") %>%
  filter(scenario != "historical" | model == histRefModel["Population"]) %>% 
  select(scenario, region, period, value) %>% 
  mutate(
    population = value * 1e6, # unit originally is million, now is 1
    value = NULL) -> 
  dataPop

data %>% 
  inner_join(pCapVariables, 'variable') %>% 
  left_join(dataPop, c('scenario', 'region', 'period')) %>% 
  mutate(
    value = value / population * conversionFactor,
    variable = paste0(variable, " pCap"),
    unit = newUnit,
    newUnit = NULL, conversionFactor = NULL, population = NULL) ->
  dataPCap

data %>% 
  bind_rows(dataPCap) ->
  data
```


```{r add gdp column}
# Create a new column gdp with the value of GDP|PPP pCap (kUS$2005).
data %>% 
  filter(variable == "GDP|PPP pCap") %>% 
  filter(scenario != "historical" | model == histRefModel["GDP|PPP pCap"]) %>% 
  select(scenario, region, period, value) %>% 
  rename(gdp = value) ->   
  dataGDP
data %>% 
  left_join(dataGDP, c('scenario', 'region', 'period')) ->
  data
```


```{r calcuate pGDP variables}
# For all variables in following table, add a new variable to data with the name
# "OldName pGDP". Calculate its value by 
#     OldValue / (GDP|PPP pCap) * conversionFactor 
# and set its unit to newUnit. 
# The new variable "OldName pGDP" will be available in the plot sections.
pGdpVariables <- tribble(
  ~variable, ~newUnit, ~conversionFactor,
  "FE", "MJ/US$2005", 1e3,
  "FE|CDR", "MJ/US$2005", 1e3,
  "FE|Transport", "MJ/US$2005", 1e3,
  "FE|Buildings", "MJ/US$2005", 1e3,
  "FE|Industry", "MJ/US$2005", 1e3)
data %>% 
  inner_join(pGdpVariables, 'variable') %>% 
  mutate(
    value = value / gdp * conversionFactor,
    variable = paste0(variable, " pGDP"),
    unit = newUnit,
    newUnit = NULL, conversionFactor = NULL) ->
  dataPGdp
data %>% 
  bind_rows(dataPGdp) ->
  data
```

```{r quitte}
data <- as.quitte(data)
```

```{r global variables}
# Set global variables for use in plotting.
options(mip.mainReg = params$mainReg)
options(mip.yearsBarPlot = params$yearsBarPlot)
options(mip.histRefModel = histRefModel)
```

```{r define plot functions}
source("cs2_plot_functions.R", local=TRUE)
```


```{r sectionPaths, include=FALSE}
if (length(params$sections) == 1 && params$sections == "all") {
  dir() %>% 
    str_subset("^csEDGET_[0-9]{2}.+//.Rmd$") %>% 
    sort() ->
    sectionPaths
} else {
  if (length(params$sections) > 0) {
    sectionPaths <- paste0("csEDGET_", params$sections, ".Rmd")
  } else {
    sectionPaths <- character(0)
  }
}
```


```{r prepare mark}
# CLICK "RUN ALL CHUNKS ABOVE" HERE TO PREPARE THE ENVIRONMENT
```


```{r include sections, child = sectionPaths}
```


```{r include user section, child = params$userSectionPath}
```
