# Prices 

```{r convert data to data table}
#convert to dplyr when time
data <- as.data.table(data)
CostReg <- params$reg
CostReg <- CostReg[!CostReg == params$mainReg]
scen <- unique(data$scenario)
```

## Prices S3S
```{r Prices S3S}

  
 
  
for (reg0 in CostReg) {
  plotdata <- data[grepl("Logit cost\\|S3\\|(Walk|Cycle|trn_pass_road|Domestic Aviation|Passenger Rail|HSR)",variable)]
  plotdata <- plotdata[region==reg0][,region:=NULL]
  plotdata <- plotdata[, variable := gsub("Logit cost\\|S3\\|","",variable)][period %in% params$yearsBarPlot]
  setnames(plotdata, "scenario","region")
  plotdata <- plotdata[, scenario:=gsub("\\|Eq inconvenience cost|\\|tot_VOT_price|\\|fuel_price_pkm|\\|non_fuel_price","",variable)]
  plotdata <- plotdata[, variable:=gsub("Walk\\||Cycle\\||trn_pass_road\\||Domestic Aviation\\||Passenger Rail\\||HSR\\|","",variable)]
  plotdata[, variable := factor(variable, levels = c("Eq inconvenience cost","tot_VOT_price","fuel_price_pkm","non_fuel_price"))]
  
  p2 <- mipBarYearData(plotdata, ylab = "Prices logit S3S [USD2005/pkm]", title = paste0("Prices logit S3S ",reg0) )
  p2 <- p2 + theme_mip(size = 18)
  print(p2)
  cat("\n\n")}

```

## Prices S2S3
```{r Prices S2S3}

for (reg0 in CostReg) {
  plotdata <- data[grepl("Logit cost\\|S2\\|(Bus|trn_pass_road_LDV)",variable)]
  plotdata <- plotdata[region==reg0][, region:=NULL]
  plotdata <- plotdata[, variable := gsub("Logit cost\\|S2\\|", "",variable)][period %in% params$yearsBarPlot]
  setnames(plotdata, "scenario","region")
  plotdata <- plotdata[, scenario := gsub("\\|Eq inconvenience cost|\\|tot_VOT_price|\\|fuel_price_pkm|\\|non_fuel_price", "", variable)]
  plotdata <- plotdata[, variable := gsub("Bus\\||trn_pass_road_LDV\\|","", variable)]
  plotdata[, variable := factor(variable, levels = c("Eq inconvenience cost","tot_VOT_price","fuel_price_pkm","non_fuel_price"))]

  p2 <- mipBarYearData(plotdata, ylab = "Prices logit S2 [USD2005/pkm]", title = paste0("Prices logit S2S3 ",reg0))
  p2 <- p2 + theme_mip(size = 18)
  print(p2)
  cat("\n\n")}

```

## Prices S1S2
```{r Prices S1S2}

for (reg0 in CostReg) {
  plotdata <- data[grepl("Logit cost\\|S1\\|(trn_pass_road_LDV_4W|trn_pass_road_LDV_2W)",variable)]
  plotdata <- plotdata[region==reg0][,region:=NULL]
  plotdata <- plotdata[, variable := gsub("Logit cost\\|S1\\|", "",variable)][period %in% params$yearsBarPlot]  
  setnames(plotdata, "scenario","region")
  plotdata <- plotdata[, scenario := gsub("\\|Eq inconvenience cost|\\|tot_VOT_price|\\|fuel_price_pkm|\\|non_fuel_price", "", variable)]
  plotdata <- plotdata[, variable := gsub("trn_pass_road_LDV_4W\\||trn_pass_road_LDV_2W\\|", "", variable)]
  plotdata[, variable := factor(variable, levels = c("Eq inconvenience cost","tot_VOT_price","fuel_price_pkm","non_fuel_price"))]
  

  p2 <- mipBarYearData(plotdata, ylab = "Prices logit S1S2 [USD2005/pkm]", title = paste0("Prices logit S1S2 ",reg0))
  p2 <- p2 + theme_mip(size = 18)
  print(p2)
  cat("\n\n")}

```

## Average LDV non fuel prices 
```{r Average LDV non fuel prices}

  plotdata <- data[grepl("Logit cost\\|S1\\|trn_pass_road_LDV_4W\\|non_fuel_price", variable) & period %in% params$yearsScen & region %in% CostReg]
  plotdata2 <- data[grepl("Logit cost\\|F\\|Average veh\\|(Liquids|BEV)\\|non_fuel_price",variable) & period %in% params$yearsScen & region %in% CostReg]
  plotdata <- rbind(plotdata,plotdata2)
  plotdata <- plotdata[, variable := gsub("Logit cost\\|S1\\||Logit cost\\|F\\|", "",variable)]
  plotdata[, variable := factor(variable, levels = c("trn_pass_road_LDV_4W|non_fuel_price","Average veh|BEV|non_fuel_price","Average veh|Liquids|non_fuel_price"))]
  # Extra plotting functions
 
  p=ggplot(plotdata, aes(x = as.character(period), y = value, color = region, linetype = variable, group = interaction(region,variable)))+
      geom_line(size = 0.5)+
      facet_wrap(~scenario, nrow = 4, scales = "free")+
      scale_x_discrete(breaks = c(2010,2030,2050,2100))+
      labs(x = "", y = paste0("Average LDV 4W non fuel prices","[", unique(data$unit),"]"), title = paste0("Average LDV 4W non fuel prices"))

  print(p)
  cat("\n\n")


```

## LDV non fuel prices for different technologies and vehicle sizes
```{r LDV non fuel prices for different technologies and vehicle sizes}

plotdata <- data[grepl("Logit cost\\|F\\|(Compact Car|Large Car|Large Car and SUV|Light Truck and SUV|Midsize Car|Mini Car|Subcompact Car|Van)\\|(Liquids|BEV)\\|non_fuel_price",variable) & period %in% params$yearsScen & region %in% CostReg]
plotdata[, variable := gsub("|Logit cost\\|F\\||\\|non_fuel_price", "",variable)]
plotdata [, technology := gsub("(Compact Car|Large Car|Large Car and SUV|Light Truck and SUV|Midsize Car|Mini Car|Subcompact Car|Van)\\|", "",variable)][, vehicleSize := gsub("\\|(Liquids|BEV)", "",variable)][, variable := NULL]

for (reg0 in CostReg) {  
  plotdata2 <- plotdata[region == reg0]
  # Extra plotting functions
 if (nrow(plotdata2)>1){
      p=ggplot(plotdata2, aes(x = as.character(period), y = value,color = vehicleSize, linetype = technology, group =
      interaction(vehicleSize,technology)))+
      geom_line(size = 0.5)+
      facet_wrap(~scenario, nrow = 4, scales = "free")+
      scale_x_discrete(breaks = c(2010,2030,2050,2100))+
      labs(x = "", y = paste0("LDV 4W non fuel prices","[", unique(data$unit),"]"), title = paste0("LDV 4W non fuel prices ", reg0))

  print(p)
  cat("\n\n")
  }}


```

## Average LDV total price
```{r Average LDV total price}

  plotdata <- data[grepl("Logit cost\\|S1\\|trn_pass_road_LDV_4W\\|",variable) & period %in%   params$yearsScen & region %in% params$reg]
  plotdata <- plotdata[, variable := gsub("Logit cost\\|S1\\|trn_pass_road_LDV_4W\\|", "",variable)]
  plotdata <- plotdata[, .(value = sum(value)), by = c("region","scenario","period","unit")]
  
  # Extra plotting functions
 
  p=ggplot(plotdata, aes(x = as.character(period), y = value, group = region, color = region))+
      geom_line(size = 0.5)+
      facet_wrap(~scenario, nrow = 4, scales = "free")+
      scale_x_discrete(breaks = c(2010,2030,2050,2100))+
      labs(x = "", y = paste0("Total LDV 4W logit costs","[", unique(data$unit),"]"), title = paste0("Total LDV 4W logit costs"))

  print(p)


```

# Shareweight trends
```{r Shareweight trends}


for (reg0 in CostReg) {

  plotdata <- data[grepl("Shareweight\\|S3\\|(Walk|Cycle|trn_pass_road|Domestic Aviation|Passenger Rail|HSR)",variable) & region == reg0]
  plotdata <- plotdata[, variable := gsub("Shareweight\\|S3\\|", "",variable)]

  p <- lineplot(varname = paste0("Shareweight trend S3 ", reg0), data = plotdata)
  print(p)
  
  cat("\n\n")
  plotdata <- data[grepl("Shareweight\\|S2\\|(Bus|trn_pass_road_LDV)",variable) & region == reg0]
  plotdata <- plotdata[, variable := gsub("Shareweight\\|S2\\|", "",variable)]
  
  p <- lineplot(varname = paste0("Shareweight trend S2 ", reg0), data = plotdata)
  print(p)
  cat("\n\n")
  
  plotdata <- data[grepl("Shareweight\\|S1\\|(trn_pass_road_LDV_2W|trn_pass_road_LDV_4W)",variable) & region == reg0]
  plotdata <- plotdata[, variable := gsub("Shareweight\\|S1\\|", "", variable)]
  
  p <- lineplot(varname = paste0("Shareweight trend S1 ", reg0), data = plotdata)
  print(p)
  cat("\n\n")}


```
