# Stock and Sales

## LDV Stock by vehicle size
```{r}
tot <- "Stock|Transport|LDV"
items <- c(
       "Stock|Transport|LDV|Compact Car",
       "Stock|Transport|LDV|Large Car",
       "Stock|Transport|LDV|Large Car and SUV",
       "Stock|Transport|LDV|Light Truck and SUV",
       "Stock|Transport|LDV|Midsize Car",
       "Stock|Transport|LDV|Mini Car",
       "Stock|Transport|LDV|Subcompact Car",
       "Stock|Transport|LDV|Van"
  )

showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Sales by vehicle size
```{r}
tot <- "Sales|Transport|LDV"
items <- c(
       "Sales|Transport|LDV|Compact Car",
       "Sales|Transport|LDV|Large Car",
       "Sales|Transport|LDV|Large Car and SUV",
       "Sales|Transport|LDV|Light Truck and SUV",
       "Sales|Transport|LDV|Midsize Car",
       "Sales|Transport|LDV|Mini Car",
       "Sales|Transport|LDV|Subcompact Car",
       "Sales|Transport|LDV|Van"
  )
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Stock by technology
```{r}
tot <- "Stock|Transport|LDV|Subcompact Car"
items <- c(
       "Stock|Transport|LDV|Subcompact Car|BEV",
       "Stock|Transport|LDV|Subcompact Car|FCEV",
       "Stock|Transport|LDV|Subcompact Car|Hybrid Electric",
       "Stock|Transport|LDV|Subcompact Car|Liquids",
       "Stock|Transport|LDV|Subcompact Car|NG"
  )
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Sales by technology
```{r}
tot <- "Sales|Transport|LDV|Subcompact Car"
items <- c(
       "Sales|Transport|LDV|Subcompact Car|BEV",
       "Sales|Transport|LDV|Subcompact Car|FCEV",
       "Sales|Transport|LDV|Subcompact Car|Hybrid Electric",
       "Sales|Transport|LDV|Subcompact Car|Liquids",
       "Sales|Transport|LDV|Subcompact Car|NG"
  )
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Stock by technology
```{r}
tot <- "Stock|Transport|LDV|Large Car and SUV"
items <- c(
       "Stock|Transport|LDV|Large Car and SUV|BEV",
       "Stock|Transport|LDV|Large Car and SUV|FCEV",
       "Stock|Transport|LDV|Large Car and SUV|Hybrid Electric",
       "Stock|Transport|LDV|Large Car and SUV|Liquids",
       "Stock|Transport|LDV|Large Car and SUV|NG"
  )
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Sales by technology
```{r}
tot <- "Sales|Transport|LDV|Large Car and SUV"
items <- c(
       "Sales|Transport|LDV|Large Car and SUV|BEV",
       "Sales|Transport|LDV|Large Car and SUV|FCEV",
       "Sales|Transport|LDV|Large Car and SUV|Hybrid Electric",
       "Sales|Transport|LDV|Large Car and SUV|Liquids",
       "Sales|Transport|LDV|Large Car and SUV|NG"
  )
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```



## Busses
```{r}
tot <- "Stock|Transport|Bus"
items <- c(
       "Stock|Transport|Bus|Electric",
       "Stock|Transport|Bus|FCEV",
       "Stock|Transport|Bus|Liquids",
       "Stock|Transport|Bus|NG"
  )

showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```


<!-- ## Truck stock by size -->
<!-- ```{r} -->
<!-- tot <- "Stock|Transport|Truck" -->
<!-- items <- c( -->
<!--        "Stock|Transport|Truck|Truck (0-3.5t)", -->
<!--        "Stock|Transport|Truck|Truck (7.5t)", -->
<!--        "Stock|Transport|Truck|Truck (18t)", -->
<!--        "Stock|Transport|Truck|Truck (26t)", -->
<!--        "Stock|Transport|Truck|Truck (40t)" -->
<!--   ) -->

<!-- showAreaAndBarPlots(data, items, tot, orderVars = "user") -->
<!-- showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user") -->
<!-- ``` -->

<!-- ## Truck sales by size -->
<!-- ```{r} -->
<!-- tot <- "Sales|Transport|Truck" -->
<!-- items <- c( -->
<!--        "Sales|Transport|Truck|Truck (0-3.5t)", -->
<!--        "Sales|Transport|Truck|Truck (7.5t)", -->
<!--        "Sales|Transport|Truck|Truck (18t)", -->
<!--        "Sales|Transport|Truck|Truck (26t)", -->
<!--        "Sales|Transport|Truck|Truck (40t)" -->
<!--   ) -->

<!-- showAreaAndBarPlots(data, items, tot, orderVars = "user") -->
<!-- showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user") -->
<!-- ``` -->

## Truck stock by technology
```{r}
tot <- "Stock|Transport|Truck"
items <- c(
       "Stock|Transport|Truck|Electric",
       "Stock|Transport|Truck|FCEV",
       "Stock|Transport|Truck|Liquids",
       "Stock|Transport|Truck|NG"
  )

showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Truck sales by technology
```{r}
tot <- "Sales|Transport|Truck"
items <- c(
       "Sales|Transport|Truck|Electric",
       "Sales|Transport|Truck|FCEV",
       "Sales|Transport|Truck|Liquids",
       "Sales|Transport|Truck|NG"
  )

showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```


<!-- ## Small Truck stock by technology -->
<!-- ```{r} -->
<!-- tot <- "Stock|Transport|Truck|Truck (0-3.5t)" -->
<!-- items <- c( -->
<!--        "Stock|Transport|Truck|Truck (0-3.5t)|Electric", -->
<!--        "Stock|Transport|Truck|Truck (0-3.5t)|FCEV", -->
<!--        "Stock|Transport|Truck|Truck (0-3.5t)|Liquids", -->
<!--        "Stock|Transport|Truck|Truck (0-3.5t)|NG" -->
<!--   ) -->

<!-- showAreaAndBarPlots(data, items, tot, orderVars = "user") -->
<!-- showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user") -->
<!-- ``` -->

<!-- ## Small Truck sales by technology -->
<!-- ```{r} -->
<!-- tot <- "Sales|Transport|Truck|Truck (0-3.5t)" -->
<!-- items <- c( -->
<!--        "Sales|Transport|Truck|Truck (0-3.5t)|Electric", -->
<!--        "Sales|Transport|Truck|Truck (0-3.5t)|FCEV", -->
<!--        "Sales|Transport|Truck|Truck (0-3.5t)|Liquids", -->
<!--        "Sales|Transport|Truck|Truck (0-3.5t)|NG" -->
<!--   ) -->

<!-- showAreaAndBarPlots(data, items, tot, orderVars = "user") -->
<!-- showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user") -->
<!-- ``` -->

<!-- ## Large Truck stock by technology -->
<!-- ```{r} -->
<!-- tot <- "Stock|Transport|Truck|Truck (40t)" -->
<!-- items <- c( -->
<!--        "Stock|Transport|Truck|Truck (40t)|Electric", -->
<!--        "Stock|Transport|Truck|Truck (40t)|FCEV", -->
<!--        "Stock|Transport|Truck|Truck (40t)|Liquids", -->
<!--        "Stock|Transport|Truck|Truck (40t)|NG" -->
<!--   ) -->

<!-- showAreaAndBarPlots(data, items, tot, orderVars = "user") -->
<!-- showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user") -->
<!-- ``` -->

<!-- ## Large Truck sales by technology -->
<!-- ```{r} -->
<!-- tot <- "Sales|Transport|Truck|Truck (40t)" -->
<!-- items <- c( -->
<!--        "Sales|Transport|Truck|Truck (40t)|Electric", -->
<!--        "Sales|Transport|Truck|Truck (40t)|FCEV", -->
<!--        "Sales|Transport|Truck|Truck (40t)|Liquids", -->
<!--        "Sales|Transport|Truck|Truck (40t)|NG" -->
<!--   ) -->

<!-- showAreaAndBarPlots(data, items, tot, orderVars = "user") -->
<!-- showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user") -->
<!-- ``` -->
