# Evaluation Sheet NAVIGATE scenarios
```{r setting}
data <- as.data.table(data)
Baseline <- "Mix2 SSP2EU"
```

```{r Calculate ES reduction rate for Passenger Cars compared to Baseline for all scenarios}
targetyear <- 2050
ES_data_base <- data[scenario == Baseline & variable == "ES|Transport|Pass|Road|LDV|Four Wheelers" & period == targetyear][, scenario := NULL]
setnames(ES_data_base, "value", "ES_base")
red_ES_pass <- merge(ES_data_base, data[!scenario == Baseline & variable == "ES|Transport|Pass|Road|LDV|Four Wheelers" & period == targetyear], all = TRUE)
red_ES_pass[, reduction_rate := round((value/ES_base)*100-100,2)]
red_ES_pass <- red_ES_pass[, c("scenario", "region", "reduction_rate")]
```

```{r Plot ES reduction rate for Passenger Cars compared to Baseline for all scenarios}
ggplot(red_ES_pass, aes(x = scenario, y = reduction_rate)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = reduction_rate), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Change [%]"), title = paste0("ES reduction rate for Passenger Cars compared to Baseline for all scenarios")) +
      facet_wrap(~region, nrow = 5, scales = "free")
```

```{r Calculate ES reduction rate for Freight compared to Baseline for all scenarios}
targetyear <- 2050
ES_data_base <- data[scenario == Baseline & grepl("ES\\|Transport\\|Freight\\|(Road|Rail)$", variable) & period == targetyear]
ES_data_base <- ES_data_base[, .(ES_Freight_land_base = sum(value)), by = "region"]
ES_data <- data[!scenario %in% c(Baseline, "historical") & grepl("ES\\|Transport\\|Freight\\|(Road|Rail)$", variable) & period == targetyear]
ES_data <- ES_data[, .(ES_Freight_land = sum(value)), by = c("scenario", "region")]
ES_data <- merge(ES_data_base, ES_data, all = TRUE)
ES_data[, reduction_rate := round((ES_Freight_land/ES_Freight_land_base)*100-100)]
ES_data <- ES_data[, c("scenario", "region", "reduction_rate")]
```

```{r Plot ES reduction rate for Freight compared to Baseline for all scenarios}
ggplot(ES_data, aes(x = scenario, y = reduction_rate)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = reduction_rate), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Change [%]"), title = paste0("Cange in ES for land-based freight transport compared to Baseline for all scenarios")) +
      facet_wrap(~region, nrow = 5,scales = "free")
```

```{r Calculate ES shares for all scenarios}
targetyear <- 2050
Pass_land <- c("ES|Transport|Pass|Rail", "ES|Transport|Pass|Road|LDV", "ES|Transport|Pass|Road|Bus", "ES|Transport|Pass|Road|Non-Motorized")
Pass_land_public <- c("ES|Transport|Pass|Road|Bus", "ES|Transport|Pass|Rail")
ES_data_land <- data[!scenario %in% c(Baseline, "historical") & variable %in% Pass_land & period == targetyear]
ES_data_land <- ES_data_land[, .(ES_Pass_land = sum(value)), by = c("region", "scenario")]
ES_data_public <- data[!scenario %in% c(Baseline, "historical") & variable %in% Pass_land_public & period == targetyear]
ES_data_public <- ES_data_public[, .(ES_Pass_public = sum(value)), by = c("region", "scenario")]
ES_data_nonmot <- data[!scenario %in% c(Baseline, "historical") & variable == "ES|Transport|Pass|Road|Non-Motorized" & period == targetyear]
ES_data_nonmot <- ES_data_nonmot[, .(ES_Pass_nonmot = sum(value)), by = c("region", "scenario")]
ES_data <- merge(ES_data_land, ES_data_public, by = c("region", "scenario"))
ES_data <- merge(ES_data, ES_data_nonmot, by = c("region", "scenario"))
ES_data[, share_public := round(ES_Pass_public/ES_Pass_land*100,2)][, ES_Pass_public := NULL]
ES_data[, share_nonmot := round(ES_Pass_nonmot/ES_Pass_land*100,2)][, ES_Pass_land := NULL][, ES_Pass_nonmot := NULL]
```

```{r Plot ES shares nonmot for all scenarios}
ggplot(ES_data, aes(x = scenario, y = share_nonmot)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = share_nonmot), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Share nonmot [%]"), title = paste0("Share of active modes in Passenger land-based transport for all scenarios")) +
      facet_wrap(~region, nrow = 5, scales = "free")
```

```{r Plot ES shares public for all scenarios}
ggplot(ES_data, aes(x = scenario, y = share_public)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = share_public), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Share public transport [%]"), title = paste0("Share of public modes in Passenger land-based transport for all scenarios")) +
      facet_wrap(~region, nrow = 5, scales = "free")
```

```{r Calculate ES reduction rate for Aviation compared to Baseline for all scenarios}
targetyear <- 2050
ES_data_base_dom <- data[scenario == Baseline & variable == "ES|Transport|Pass|Aviation|Domestic" & period == targetyear]
ES_data_base_int <- data[scenario == Baseline & variable == "ES|Transport|Pass|Aviation|International" & period == targetyear]
setnames(ES_data_base_dom, "value", "ES_dom_base")
setnames(ES_data_base_int, "value", "ES_int_base")
ES_data_base <- merge(ES_data_base_dom[, c("region", "ES_dom_base")], ES_data_base_int[, c("region", "ES_int_base")])

ES_data_dom <- data[!scenario %in% c(Baseline, "historical") & variable == "ES|Transport|Pass|Aviation|Domestic" & period == targetyear]
ES_data_int <- data[!scenario %in% c(Baseline, "historical") & variable == "ES|Transport|Pass|Aviation|International" & period == targetyear]
setnames(ES_data_dom, "value", "ES_dom")
setnames(ES_data_int, "value", "ES_int")
ES_data <- merge(ES_data_dom[, c("region", "ES_dom", "scenario")], ES_data_int[, c("region", "ES_int", "scenario")])

ES_data <- merge(ES_data_base, ES_data, all = TRUE)
ES_data[, reduction_rate_int := round((ES_int/ES_int_base)*100-100)]
ES_data[, reduction_rate_dom := round((ES_dom/ES_dom_base)*100-100)]
ES_data <- ES_data[, c("scenario", "region", "reduction_rate_int", "reduction_rate_dom")]
```

```{r Plot ES reduction rate for Aviation dom compared to Baseline for all scenarios}
ggplot(ES_data, aes(x = scenario, y = reduction_rate_dom)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = reduction_rate_dom), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Change [%]"), title = paste0("Cange in ES for domestic passenger avitaion compared to Baseline for all scenarios")) +
      facet_wrap(~region, nrow = 5, scales = "free")
```

```{r Plot ES reduction rate for Aviation int compared to Baseline for all scenarios}
ggplot(ES_data, aes(x = scenario, y = reduction_rate_int)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = reduction_rate_int), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Change [%]"), title = paste0("Cange in ES for international passenger avitaion compared to Baseline for all scenarios")) +
      facet_wrap(~region, nrow = 5, scales = "free")
```



```{r Calculate ES reduction rate for Freight shipping compared to Baseline for all scenarios}
targetyear <- 2050
ES_data_base <- data[scenario == Baseline & grepl("ES\\|Transport\\|Freight\\|(International Shipping|Navigation)$", variable) & period == targetyear]
ES_data_base <- ES_data_base[, .(ES_Freight_shipping_base = sum(value)), by = "region"]
ES_data <- data[!scenario %in% c(Baseline, "historical") & grepl("ES\\|Transport\\|Freight\\|(International Shipping|Navigation)$", variable) & period == targetyear]
ES_data <- ES_data[, .(ES_Freight_shipping = sum(value)), by = c("scenario", "region")]
ES_data <- merge(ES_data_base, ES_data, all = TRUE)
ES_data[, reduction_rate := round((ES_Freight_shipping/ES_Freight_shipping_base)*100-100)]
ES_data <- ES_data[, c("scenario", "region", "reduction_rate")]
```

```{r Plot ES reduction rate for Freight shipping compared to Baseline for all scenarios}
ggplot(ES_data, aes(x = scenario, y = reduction_rate)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = reduction_rate), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Change [%]"), title = paste0("Cange in ES for freight shipping compared to Baseline for all scenarios")) +
      facet_wrap(~region, nrow = 5, scales = "free")
```

```{r Calculate Share of H2 in aviation (international+domestic) for all scenarios}
targetyear <- 2070
FE_data_h2 <- data[!scenario %in% c(Baseline, "historical") & grepl("FE\\|Transport\\|Pass\\|Aviation\\|Domestic\\|Hydrogen$", variable) & period == targetyear]
setnames(FE_data_h2, "value", "FE_h2")
FE_data <- data[!scenario %in% c(Baseline, "historical") & grepl("FE\\|Transport\\|Pass\\|Aviation$", variable) & period == targetyear]
FE_data <- merge(FE_data_h2[, c("region", "scenario", "FE_h2")], FE_data[, c("region", "scenario", "value")])
FE_data[, shareh2 := round((FE_h2/value)*100)]
FE_data <- FE_data[, c("scenario", "region", "shareh2")]
```

```{r Plot Share of H2 in aviation (international+domestic) for all scenarios}
ggplot(FE_data, aes(x = scenario, y = shareh2)) +
      geom_bar(stat="identity") + 
      geom_label(aes(label = shareh2), vjust = 0.5, colour = "black") +
      labs(x = "Scenario", y = paste0("Change [%]"), title = paste0("Share of H2 in aviation (international+domestic) for all scenarios")) +
      facet_wrap(~region, nrow = 5, scales = "free")
```
