# Emissions

## Emissions Passenger
```{r}
tot <- "Emi|CO2|Transport|Pass|w/o bunkers|Tailpipe"
items <- c(
  "Emi|CO2|Transport|Pass|Aviation|International|Tailpipe",
  "Emi|CO2|Transport|Pass|Aviation|Domestic|Tailpipe",
  "Emi|CO2|Transport|Pass|Rail|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|Bus|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|LDV|Four Wheelers|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|LDV|Two Wheelers|Tailpipe"
)

showAreaAndBarPlots(data, items[2:6], tot, orderVars = "user")
showAreaAndBarPlots(data, items[2:6], tot, fill = TRUE, orderVars = "user")
showLinePlots(data, tot)
walk(c(
  items, "Emi|CO2|Transport|Pass|Road|LDV|Tailpipe",
  "Emi|CO2|Transport|Pass|non-LDV|Tailpipe"
), showLinePlots, data = data)
```

## Emissions LDV Four Wheelers
```{r}
tot <- "Emi|CO2|Transport|Pass|Road|LDV|Four Wheelers|Tailpipe"
items <- c(
  "Emi|CO2|Transport|Pass|Road|LDV|Van|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|LDV|SUV|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|LDV|Large|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|LDV|Medium|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|LDV|Small|Tailpipe",
  "Emi|CO2|Transport|Pass|Road|LDV|Mini|Tailpipe"
)

showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
showLinePlots(data, tot)
walk(items, showLinePlots, data = data)
```

## Emissions Freight
```{r}
tot <- "Emi|CO2|Transport|Freight|w/o bunkers|Tailpipe"
items <- c(
  "Emi|CO2|Transport|Freight|International Shipping|Tailpipe",
  "Emi|CO2|Transport|Freight|Navigation|Tailpipe",
  "Emi|CO2|Transport|Freight|Rail|Tailpipe",
  "Emi|CO2|Transport|Freight|Road|Tailpipe"
)
showAreaAndBarPlots(data, items[2:4], tot, orderVars = "user")
showAreaAndBarPlots(data, items[2:4], tot_wobunk, fill = TRUE, orderVars = "user")
showLinePlots(data, tot)
walk(items, showLinePlots, data = data)
```      

## Emissions Freight Road      
```{r}
tot <- "Emi|CO2|Transport|Freight|Road|Tailpipe"
items <- c(
  "Emi|CO2|Transport|Freight|Road|Truck (40t)|Tailpipe",
  "Emi|CO2|Transport|Freight|Road|Truck (26t)|Tailpipe",
  "Emi|CO2|Transport|Freight|Road|Truck (18t)|Tailpipe",
  "Emi|CO2|Transport|Freight|Road|Truck (7.5t)|Tailpipe",
  "Emi|CO2|Transport|Freight|Road|Truck (0-3.5t)|Tailpipe"
)

showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
showLinePlots(data, tot)
walk(items, showLinePlots, data = data)
```      
      
