---
title: "Transport Validation"
output:
  word_document: default
  html_document:
      code_folding: hide
  html_notebook:
      code_folding: hide
  pdf_document: default
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Settings, echo=FALSE}
rm(list=ls())
library(magclass)
library(lusweave)
library(mip)
library(luplot)
library(ggplot2) 
library(quitte) 
library(data.table)
library(utils)
library(rmndt)
library(remind2)
library(madrat)
library(devtools)
load_all("C:/Users/johannah/Documents/EDGE-Transport/Git_clones/edgeTransport")
```

```{r Settings, echo=FALSE}
output_folder="C:/Users/johannah/Documents/EDGE-Transport/Output"
listofruns= list(
  "C:/Users/johannah/Documents/EDGE-Transport/Output/SSP2Refgd40Ref-Mix_2021-12-10_10.25.26",
  "C:/Users/johannah/Documents/EDGE-Transport/Output/SSP2Refgd40Ref_Val4-Mix_2021-12-10_12.25.47", 
  "C:/Users/johannah/Documents/EDGE-Transport/Output/SSP2Refgd40Ref_Val5-Mix_2021-12-10_12.41.08", 
  "C:/Users/johannah/Documents/EDGE-Transport/Output/SSP2Refgd40Ref_Val7-Mix_2021-12-10_13.12.17")

y_bar=c(2010,2030,2050,2100)
reg=NULL
mainReg="GLO"
fileName=paste0("Transport_Val_",format(Sys.time(), "%Y-%m-%d_%H.%M.%S"),".pdf")
sr15marker_RCP=NULL
mrremind_folder="C:/Users/johannah/Documents/EDGE-Transport/EDGE-T_standalone_InputData/mrremind"
load_Cache=TRUE
AggrReg="H12"
# load plotdata
data <- lvl2_generate_plotdata(listofruns, load_Cache, mrremind_folder, AggrReg)

#load historical data 

 ## ---- Read historical data ----
  items <- c("IEA ETP RTS","IEA ETP 2DS","IEA ETP B2DS","IEA","JRC")
  historical <- read.report("C:/Users/johannah/Documents/EDGE-Transport/compScens_vgl_REMIND/CompScen_mifs/historical.mif", as.list = F)
  historical <- historical[,,items, pmatch = F]
  # Clean zeros and global data for JRC
  historical@.Data[historical@.Data == 0] = NA 
  historical["GLO",,"JRC", pmatch = F] = NA

```

## FE Transport

```{r, fig.width=8, fig.height=9}

mainReg <- "GLO"

vars <- c(
  "FE|Transport (EJ/yr)",
  "FE|Transport|Pass (EJ/yr)",
  "FE|Transport|Pass|Rail (EJ/yr)",
  "FE|Transport|Pass|Road|Bus (EJ/yr)",
  "FE|Transport|Pass|Road|LDV (EJ/yr)",
  "FE|Transport|Freight (EJ/yr)",
  "FE|Transport|Freight|Navigation (EJ/yr)",
  "FE|Transport|Freight|Rail (EJ/yr)",
  "FE|Transport|Freight|Road (EJ/yr)")

for (var0 in vars) {
  if (sub(" (.*)", "",var0) %in% unique(data$LinePlot_data$variable)) {
    p1 <- mipLineHistorical(
      data$LinePlot_data[region==mainReg & variable==sub(" (.*)", "",var0)],
      x_hist = historical[mainReg, , var0],
      ylab = var0,
      scales = "free_y",
      xlim = c(1990, 2050)
    )
    print(p1)
    p2 <- mipLineHistorical(data$LinePlot_data[!region==mainReg & variable==sub(" (.*)", "",var0)],
      x_hist = historical[, , var0][mainReg, , , invert = TRUE],
      ylab = var0, scales = "free_y", plot.priority = c("x_hist", "x", "x_proj"), facet.ncol = 3,
      xlim = c(1990, 2050)
    )
    print(p2)
  } else {
    print(paste0(var0, " not in runs"))
  }
}
```

## ES Transport

```{r, fig.width=8, fig.height=9}

mainReg <- "GLO"

vars <- c(
  "ES|Transport|Pass (bn pkm/yr)",
  "ES|Transport|Pass|Road|LDV (bn pkm/yr)" , 
  "ES|Transport|Pass|Road|Bus (bn pkm/yr)",
  "ES|Transport|Pass|Long distance (bn pkm/yr)",
  "ES|Transport|Pass|Rail (bn pkm/yr)",
  "ES|Transport|Freight|Road (bn tkm/yr)", 
  "ES|Transport|Freight|Rail (bn tkm/yr)"
)

for (var0 in vars) {
  if (var0 %in% var0 %in% unique(data$LinePlot_data$variable)) {
    p1 <- mipLineHistorical(
      data$LinePlot_data[region==mainReg & variable==var0],
      x_hist = historical[mainReg, , var0],
      ylab = var0,
      scales = "free_y",
      xlim = c(1990, 2050)
    )
    print(p1)
    p2 <- mipLineHistorical(data$LinePlot_data[!region==mainReg & variable==var0],
      x_hist = historical[, , var0][mainReg, , , invert = TRUE],
      ylab = var0, scales = "free_y", plot.priority = c("x_hist", "x", "x_proj"), facet.ncol = 3,
      xlim = c(1990, 2050)
    )
    print(p2)
  } else {
    print(paste0(var0, " not in runs"))
  }
}
```

## EInt Transport

```{r, fig.width=8, fig.height=9}

mainReg <- "GLO"

vars <- c(
  "EInt|Transport|Pass (bn pkm/yr)",
  "EInt|Transport|Pass|Road|LDV (bn pkm/yr)" , 
  "EInt|Transport|Pass|Road|Bus (bn pkm/yr)",
  "EInt|Transport|Pass|Long distance (bn pkm/yr)",
  "EInt|Transport|Pass|Rail (bn pkm/yr)",
  "EInt|Transport|Freight|Road (bn tkm/yr)", 
  "EInt|Transport|Freight|Rail (bn tkm/yr)"
)

for (var0 in vars) {
  if (var0 %in% var0 %in% unique(data$LinePlot_data$variable)) {
    p1 <- mipLineHistorical(
      data$LinePlot_data[region==mainReg & variable==var0],
      x_hist = historical[mainReg, , var0],
      ylab = var0,
      scales = "free_y",
      xlim = c(1990, 2050)
    )
    print(p1)
    p2 <- mipLineHistorical(data$LinePlot_data[!region==mainReg & variable==var0],
      x_hist = historical[, , var0][mainReg, , , invert = TRUE],
      ylab = var0, scales = "free_y", plot.priority = c("x_hist", "x", "x_proj"), facet.ncol = 3,
      xlim = c(1990, 2050)
    )
    print(p2)
  } else {
    print(paste0(var0, " not in runs"))
  }
}

```


## Prices S2S3

```{r, fig.width=8, fig.height=9}

  p1 <- mipBarYearData(data$Prices_S2S3_Plot_data_LDV[period %in% c(2010,2020, 2030, 2050)],ylab="Prices logit_S2S3 LDV [USD2005/pkm]")
  print(p1)
  p2 <- mipBarYearData(data$Prices_S2S3_Plot_data_Bus[period %in% c(2010,2020, 2030, 2050)],ylab="Prices logit_S2S3 Bus [USD2005/pkm]")
  print(p2)

```  


```{r Line plot per cap, echo=FALSE}

lineplots_perCap <- function(data, vars, percap_factor, ylabstr,
                               global=FALSE, mainReg_plot=mainReg, per_gdp=FALSE, histdata_plot=NULL){
    
    
    ## models for historical data
    histmap = list(
      "Population"="WDI",
      "GDP|PPP"="James_IMF",
      "FE"="IEA",
      "FE|Transport"="IEA",
      "FE|Buildings"="IEA",
      "FE|Industry"="IEA"
    )
    
    items <- c(vars,
               "Population (million)",
               "GDP|PPP (billion US$2005/yr)")
    var <- as.data.table(as.quitte(data[,, items]))[, "unit" := NULL]
    
    plain_items <- gsub("(.+) \\(.+\\)", "\\1", items)
    
    if(!is.null(histdata_plot)){
      if(!all(items %in% getNames(histdata_plot, dim=3))){
        missing <- items[!items %in% getNames(histdata_plot, dim=3)]
        stop(paste("Items missing in historical dataset:",
                   paste(missing, collapse=", ")))
      }else if(!all(plain_items %in% names(histmap))){
        missing <- items[!plain_items %in% names(histmap)]
        stop(paste("No model defined for item in historical dataset:",
                   paste(missing, collapse=", ")))
      }else{
        hist_dt <- as.data.table(as.quitte(histdata_plot[,, items]))
        models <- unlist(histmap[plain_items])
        varhist <- hist_dt[
          model %in% models][ # IEA: energy, IMF: GDP, WDI: Population
            , c("unit", "model") := list(NULL, "REMIND")]
        var <- rbind(var, varhist)
      }
    }
    
    plain_vars <- gsub("(.+) \\(.+\\)", "\\1", vars)
    
    variable <- Population <- NULL
    region <- `GDP|PPP` <- model <- value <- scenario <- NULL
    
    hvar <- data.table::dcast(var, ... ~ variable)
    
    for(fe in plain_vars){
      hvar[, (fe) := get(fe)/Population*percap_factor]
    }
    
    if(per_gdp){
      hvar[, `GDP|PPP` := `GDP|PPP`/Population]
      var <- data.table::melt(hvar, id.vars=c("model", "scenario", "region", "period", "GDP|PPP"))
    }else{
      hvar[, `GDP|PPP` := NULL]
      var <- data.table::melt(hvar, id.vars=c("model", "scenario", "region", "period"))
    }
    
    var <- var[variable != "Population"][
      , variable := factor(variable, levels=plain_vars)]
    
    highlight_yrs <- c(2030, 2050, 2070)
    highlights <- var[scenario != "historical" & period %in% highlight_yrs]
    
    reg_cols <- plotstyle(as.character(unique(var$region)))
    reg_labels <- plotstyle(as.character(unique(var$region)), out="legend")
    
    var <- var[value > 0]
    if(per_gdp){
      if(global){
        p <- ggplot() +
          geom_line(data=var[scenario != "historical" & region == mainReg_plot],
                    aes(x=`GDP|PPP`, y=value, linetype=scenario)) +
          geom_point(data=var[scenario == "historical" & region == mainReg_plot],
                     aes(x=`GDP|PPP`, y=value), shape=4) +
          geom_point(data=highlights[region == mainReg_plot], aes(x=`GDP|PPP`, y=value), shape=1)
      }else{
        p <- ggplot() +
          geom_line(data=var[scenario != "historical" & region != mainReg_plot],
                    aes(x=`GDP|PPP`, y=value, linetype=scenario, color=region)) +
          geom_point(data=var[scenario == "historical" & region != mainReg_plot],
                     aes(x=`GDP|PPP`, y=value, color=region), shape=4) +
          geom_point(data=highlights[region != mainReg_plot], aes(x=`GDP|PPP`, y=value, color=region), shape=1) +
          scale_color_manual(values = reg_cols,  labels = reg_labels)
      }
      
      p <- p +
        facet_wrap(~ variable, scales="free_y") +
        ylab(ylabstr) +
        xlab("GDP PPP per Cap. (kUS$2005)") +
        expand_limits(y=0) +							
        theme_minimal()
      
    }else{
      if(global){
        p <- ggplot() +
          geom_line(data=var[scenario != "historical" & region == mainReg_plot],
                    aes(x=period, y=value, linetype=scenario)) +
          geom_point(data=var[scenario == "historical" & region == mainReg_plot],
                     aes(x=period, y=value), shape=4)
      }else{
        p <- ggplot() +
          geom_line(data=var[scenario != "historical" & region != mainReg_plot],
                    aes(x=period, y=value, linetype=scenario, color=region)) +
          geom_point(data=var[scenario == "historical" & region != mainReg_plot],
                     aes(x=period, y=value, color=region), shape=4) +
          scale_color_manual(values = reg_cols,  labels = reg_labels)
      }
      p <- p +
        facet_wrap(~ variable, scales="free_y") +
        xlab("year") +
        ylab(ylabstr) +
        expand_limits(y=0) +
        theme_minimal()
      
    }
    return(p)
  }


```




























