---
title: "Validation EDGE-Transport model"
output:
  html_document:
  df_print: paged
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
require(ggplot2)
require(data.table)
require(dplyr)
require(remind)
require(gdxdt)
require(gdx)
require(rmndt)
require(quitte)
require(gridExtra)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
cols <- c("NG" = "#d11141",
          "Liquids" = "#8c8c8c",
          "Hybrid Liquids" = "#ffc425",
          "Hybrid Electric" = "#f37735",
          "BEV" = "#00b159",
          "Electricity" = "#00b159",
          "Electric" = "#00b159",
          "FCEV" = "#00aedb",
          "pchar" = "#00aedb",
          "pinco_tot" = "#00b159",
          "pmod_av" = "#f37735",
          "prange" = "#ffc425",
          "pref" = "#8c8c8c",
          "prisk" = "#d11141",
          "Hydrogen" = "#00aedb",
          "Biodiesel" = "#66a182",
          "Synfuel" = "orchid",
          "Oil" = "#2e4057",
          "fuel price pkm" = "#edae49",
          "Operating costs registration and insurance" = "#8d96a3",
          "Operating costs maintenance" = "#00798c",
          "Capital cost" = "#d1495b",
          "International Aviation" = "#9acd32",
          "AVBUNK" = "#9acd32",
          "Domestic Aviation" = "#7cfc00",
          "DOMESAIR" = "#7cfc00",
          "Bus" = "#32cd32",
          "Passenger Rail" = "#2e8b57",
          "RAIL" = "#2e8b57",
          "Freight Rail" = "#ee4000",
          "Trucks" = "#ff6a6a",
          "ROAD" = "#ff6a6a",
          "International Shipping" = "#cd2626",
          "MARBUNK" = "#cd2626",
          "Domestic Shipping" = "#ff4040",
          "DOMESNAV" = "#ff4040",
          "Shipping" = "#ff4040",
          "Truck" = "#ff7f50",
          "Trucks (<3.5t)" = "#ff7f50",
          "Trucks (3.5t-16)" = "#8b0000",
          "Trucks (>16)" = "#fa8072",
          "Motorbikes" = "#1874cd", #"dodgerblue3",
          "Small Cars" = "#87cefa",
          "Large Cars" = "#6495ed",
          "Van" = "#40e0d0",
          "LDV" = "#00bfff",
          "Non motorized" = "#da70d6",
          "Freight"="#ff0000",
          "Freight (Inland)" = "#cd5555",
          "Pass non LDV" = "#6b8e23",
          "Pass" = "#66cdaa",
          "Pass non LDV (Domestic)" = "#54ff9f",
          "refined liquids enduse" = "#8c8c8c")

datapath <- function(fname){
  file.path("./", fname)
}

## load input data from last EDGE run
demand_km <- readRDS(datapath(fname = "demandF_plot_pkm.RDS")) ## detailed energy services demand, million km
demand_ej <- readRDS(datapath(fname = "demandF_plot_EJ.RDS")) ## detailed final energy demand, EJ
vintcomp <- readRDS(datapath(fname = "vintcomp.RDS"))
newcomp <- readRDS(datapath(fname = "newcomp.RDS"))
shares <- readRDS(datapath(fname = "shares.RDS"))
pref <- readRDS(datapath(fname = "pref_output.RDS"))
mj_km_data <- readRDS(datapath(fname = "mj_km_data.RDS"))
loadFactor <- readRDS(datapath(fname = "loadFactor.RDS"))
## Load population to calculate per capita values
POP = readRDS(datapath(fname = "POP.RDS"))
## load IEA data as a comparison
IEA = readRDS(datapath(fname = "IEAcomp.RDS"))
```




# Inconvenience cost trend

```{r, echo=FALSE, warning=FALSE, message=FALSE}

plotinconv = function(inco_tech, vt){
  p=ggplot()+
    geom_bar(data = inco_tech[subsector_L1 == "trn_pass_road_LDV_4W" & vehicle_type == vt & year<=2100 & year>=2010], aes(x = as.character(year), y = value, group = logit_type, fill = logit_type), position = position_stack(), stat = "identity")+
    facet_grid(region~technology, scales = "free")+
    theme_minimal()+
    expand_limits(y = c(0,0.8))+
    scale_x_discrete(breaks = c(2015,2050,2100))+
    theme(axis.text.x = element_text(angle = 90, vjust = +0.1),
          strip.background = element_rect(color = "grey"))+
    scale_fill_manual(values = cols)+
    labs(x = "", y = "Inconvenience cost [$/pkm]", title = paste0("Example of ", vt))

  return(p)
}

plotinconv(inco_tech = pref$FV_final_pref, vt = "Large Car and SUV")
plotinconv(inco_tech = pref$FV_final_pref, vt = "Midsize Car")
plotinconv(inco_tech = pref$FV_final_pref, vt = "Subcompact Car")

```


# Final energy demand

```{r, echo=FALSE, warning=FALSE, message=FALSE}
demandEJplotf = function(demandEJ, POP){
  ## EDGE results
  demandEJ <- demandEJ[, c("sector", "subsector_L3", "subsector_L2", "subsector_L1", "vehicle_type", "technology", "region", "year", "demand_EJ")]

  ## attribute aggregated mode and vehicle names for plotting purposes, and aggregate
  demandEJ[, aggr_mode := ifelse(subsector_L2 == "trn_pass_road_LDV", "LDV", NA)]
  demandEJ[, aggr_mode := ifelse(subsector_L3 %in% c("Passenger Rail", "HSR", "International Aviation", "Domestic Aviation"), "Pass non LDV", aggr_mode)]
  demandEJ[, aggr_mode := ifelse(subsector_L2 %in% c("trn_pass_road_bus", "Bus"), "Pass non LDV", aggr_mode)]
  demandEJ[, aggr_mode := ifelse(is.na(aggr_mode), "Freight", aggr_mode)]
  demandEJ[, veh := ifelse(grepl("Large|SUV|Midsize|Multipurpose Vehicle|Van|3W Rural", vehicle_type), "Large Cars", NA)]
  demandEJ[, veh := ifelse(grepl("Subcompact|Compact|Mini", vehicle_type), "Small Cars", veh)]
  demandEJ[, veh := ifelse(grepl("Motorcycle|Moped|Scooter", vehicle_type), "Motorbikes", veh)]
  demandEJ[, veh := ifelse(grepl("bus|Bus", vehicle_type), "Bus", veh)]
  demandEJ[, veh := ifelse(grepl("Truck", vehicle_type) & vehicle_type != "Light Truck and SUV", "Truck", veh)]
  demandEJ[, veh := ifelse(grepl("Freight Rail_tmp_vehicletype", vehicle_type), "Freight Rail", veh)]
  demandEJ[, veh := ifelse(grepl("Passenger Rail|HSR", vehicle_type), "Passenger Rail", veh)]
  demandEJ[, veh := ifelse(subsector_L3 == "Domestic Ship", "Domestic Shipping", veh)]
  demandEJ[, veh := ifelse(subsector_L3 == "International Ship", "International Shipping", veh)]
  demandEJ[, veh := ifelse(subsector_L3 == "Domestic Aviation", subsector_L3, veh)]
  demandEJ[, veh := ifelse(subsector_L3 == "International Aviation", subsector_L3, veh)]
  demandEJ[, veh := ifelse(is.na(veh), vehicle_type, veh)]
  demandEJ = demandEJ[,.(demand_EJ, region, year, aggr_mode, veh)]

  demandEJ[, vehicle_type_plot := factor(veh, levels = c("LDV","Freight Rail", "Truck","Domestic Shipping", "International Shipping",
                                                         "Motorbikes", "Small Cars", "Large Cars", "Van",
                                                         "Domestic Aviation", "International Aviation", "Bus", "Passenger Rail",
                                                         "Freight", "Freight (Inland)", "Pass non LDV", "Pass non LDV (Domestic)"))]

  legend_ord <- c("Freight Rail", "Truck", "International Shipping","Domestic Shipping",
                  "Motorbikes", "Small Cars", "Large Cars", "Van",
                  "International Aviation", "Domestic Aviation","Bus", "Passenger Rail",
                  "Freight", "LDV", "Pass non LDV", "Freight (Inland)", "Pass non LDV (Domestic)")
  demandEJ = demandEJ[,.(demand_EJ = sum(demand_EJ)), by = .(region, year, vehicle_type_plot, aggr_mode)]

  demandEJglob = demandEJ[,.(demand_EJ = sum(demand_EJ)), by = .(year, vehicle_type_plot, aggr_mode)][, region:= "World"]

  demandEJ = rbind(demandEJglob,demandEJ)
  ## calculate per capita demand
  demandEJcap = merge(demandEJ , POP, all.x = TRUE, by =c("year", "region"))
  demandEJcapglob = demandEJcap[,.(demand_EJ = sum(demand_EJ), value = sum(value)), by = .(year, vehicle_type_plot, aggr_mode)][, region:= "World"]

  demandEJcap = rbind(demandEJcap, demandEJcapglob)

  ## calculate per capita values
  demandEJcap = demandEJcap[order(aggr_mode)]
  demandEJcap[, cap_dem := demand_EJ*    ## in EJ
                1e+09/        ## in GJ
                value*          ## in million km
                1e-6]          ## in people/millionpeople=GJ/person


  ppass=ggplot()+
    geom_area(data = demandEJ[year > 2005 & aggr_mode %in% c("LDV", "Pass non LDV")], aes(x=year, y=demand_EJ, group = interaction(vehicle_type_plot,aggr_mode), fill = vehicle_type_plot), color = "black", position= position_stack())+
    facet_wrap(~region, nrow = 4, scales = "free")+
    labs(x = "", y = "Passenger final Energy demand [EJ]")+
    theme_minimal()+
    scale_fill_manual(values = cols)+
    # scale_fill_manual("Vehicle Type",values = cols, breaks=legend_ord)+
    theme(axis.text.x = element_text(size = 8),
          axis.text.y = element_text(size=8),
          axis.title = element_text(size = 9),
          title = element_text(size = 9),
          legend.text = element_text(size = 9),
          legend.title = element_text(size =9),
          strip.text = element_text(size=9))

  pfreight=ggplot()+
    geom_area(data = demandEJ[year > 2010 & aggr_mode %in% c("Freight")], aes(x=year, y=demand_EJ, group = interaction(vehicle_type_plot,aggr_mode), fill = vehicle_type_plot), color = "black", position= position_stack())+
    facet_wrap(~region, nrow = 4, scales = "free")+
    labs(x = "", y = "Freight final Energy demand [EJ]")+
    theme_minimal()+
    scale_fill_manual(values = cols)+
    # scale_fill_manual("Vehicle Type",values = cols, breaks=legend_ord)+
    theme(axis.text.x = element_text(size = 8),
          axis.text.y = element_text(size=8),
          axis.title = element_text(size = 9),
          title = element_text(size = 9),
          legend.text = element_text(size = 9),
          legend.title = element_text(size =9),
          strip.text = element_text(size=9))


  pcap=ggplot()+
    geom_area(data = demandEJcap[year > 2020], aes(x=year, y=cap_dem, group = interaction(vehicle_type_plot,aggr_mode), fill = vehicle_type_plot), color = "black", position= position_stack())+
    facet_wrap(~region, nrow = 4, scales = "free")+
    labs(x = "", y = "Final Energy demand [GJ/cap]")+
    theme_minimal()+
    scale_fill_manual(values = cols)+
    # scale_fill_manual("Vehicle Type",values = cols, breaks=legend_ord)+
    theme(axis.text.x = element_text(size = 8),
          axis.text.y = element_text(size=8),
          axis.title = element_text(size = 9),
          title = element_text(size = 9),
          legend.text = element_text(size = 9),
          legend.title = element_text(size =9),
          strip.text = element_text(size=9))



  return(list(ppass = ppass, pfreight = pfreight, pcap = pcap))
}

## Final Energy demand
demEJ = demandEJplotf(demand_ej, POP)
demEJ
```

# LDVs final energy demand

```{r, echo=FALSE, warning=FALSE, message=FALSE}
## demand EJ for LDV, divided by fuel type

demandEJLDVplotf <- function(demandEJ){
  demandEJ = demandEJ[subsector_L1 == "trn_pass_road_LDV_4W",]
  demandEJ <- demandEJ[, c("sector", "subsector_L3", "subsector_L2", "subsector_L1", "vehicle_type", "technology", "region", "year", "demand_EJ")]

  demandEJ[technology == "Hybrid Liquids", technology := "Liquids"]
  demandEJ[technology == "FCEV", technology := "Hydrogen"]
  demandEJ[technology == "BEV", technology := "Electricity"]
  demandEJ = demandEJ[, .(demand_EJ = sum(demand_EJ)), by = c("region", "year", "technology")]

  demandEJglob = demandEJ[, .(demand_EJ = sum(demand_EJ)), by = c("year", "technology")][, region := "World"]

  p = ggplot()+
    geom_area(data = demandEJ[year > 2010], aes(x=year, y=demand_EJ, group = technology, fill = technology), color="black",position= position_stack())+
    labs(x = "", y = "Final energy demand for LDVs [EJ]")+
    facet_wrap(~region, nrow = 4, scales = "free")+
    scale_fill_manual(values = cols)+
    theme_minimal()+
    # scale_fill_manual("Vehicle Type",values = cols, breaks=legend_ord)+
    theme(axis.text.x = element_text(size = 7),
          axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8))

  return(p)

}


demandEJLDVplotf(demand_ej)
```

# Trucks final energy demand

```{r, echo=FALSE, warning=FALSE, message=FALSE}
## demand EJ for trucks, divided by fuel type

demandEJTruckplotf <- function(demandEJ){
  demandEJ = demandEJ[subsector_L3 == "trn_freight_road",]
  demandEJ <- demandEJ[, c("sector", "subsector_L3", "vehicle_type", "technology", "region", "year", "demand_EJ")]

  demandEJ[technology == "Hybrid Liquids", technology := "Liquids"]
  demandEJ[technology == "FCEV", technology := "Hydrogen"]
  demandEJ[technology == "BEV", technology := "Electricity"]
  demandEJ = demandEJ[, .(demand_EJ = sum(demand_EJ)), by = c("region", "year", "technology")]

  demandEJglob = demandEJ[, .(demand_EJ = sum(demand_EJ)), by = c("year", "technology")][, region := "World"]

  p = ggplot()+
    geom_area(data = demandEJ[year > 2010], aes(x=year, y=demand_EJ, group = technology, fill = technology), color="black",position= position_stack())+
    labs(x = "", y = "Final energy demand for trucks [EJ]")+
    facet_wrap(~region, nrow = 4, scales = "free")+
    scale_fill_manual(values = cols)+
    theme_minimal()+
    theme(axis.text.x = element_text(size = 7),
          axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8))

  return(p)

}


demandEJTruckplotf(demand_ej)
```

# FE comparison IEA historical data vs EDGE-T projections


```{r, echo=FALSE, warning=FALSE, message=FALSE}
## demand EJ for trucks, divided by fuel type

demandEJ_IEAcomp <- function(demandEJ, IEA){

  demandEJ[, flow := ifelse(sector == "trn_aviation_intl", "AVBUNK", NA)]
  demandEJ[, flow := ifelse(sector == "trn_shipping_intl", "MARBUNK", flow)]
  demandEJ[, flow := ifelse(grepl("road", subsector_L3), "ROAD", flow)]
  demandEJ[, flow := ifelse(grepl("Rail|HSR", subsector_L3), "RAIL", flow)]
  demandEJ[, flow := ifelse(grepl("Domestic Aviation", subsector_L3), "DOMESAIR", flow)]
  demandEJ[, flow := ifelse(grepl("Domestic Ship", subsector_L3), "DOMESNAV", flow)]
  demandEJ = demandEJ[,.(value = sum(demand_EJ)), by = c("region", "year", "flow")]
  demandEJ[, model := "EDGE-T"]
  IEA[, model := "IEAbal"]
  totdem=rbind(demandEJ[year>=2015], IEA[year<2015])

  p1 = ggplot()+
    geom_area(data = totdem[flow=="ROAD"], aes(x=year, y=value, group = interaction(model, flow), fill = flow), color="black",position= position_stack())+
    labs(x = "", y = "Final energy demand road [EJ]")+
    facet_wrap(~region, nrow = 4, scales = "free")+
    scale_fill_manual(values = cols)+
    theme_minimal()+
    theme(axis.text.x = element_text(size = 7),
          axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8))

    p2 = ggplot()+
    geom_area(data = totdem[flow!="ROAD"], aes(x=year, y=value, group = interaction(model, flow), fill = flow), color="black",position= position_stack())+
    labs(x = "", y = "Final energy demand no road [EJ]")+
    facet_wrap(~region, nrow = 4, scales = "free")+
    scale_fill_manual(values = cols)+
    theme_minimal()+
    theme(axis.text.x = element_text(size = 7),
          axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8))
    totdem1=rbind(demandEJ, IEA)
    p3 = ggplot()+
    geom_bar(data = totdem1[year %in% c(2005, 2010, 2015) & flow =="ROAD"], aes(x=model, y=value, group = interaction(model, flow), fill = flow), color="black", position="stack", stat = "identity", width = 0.5)+
    labs(x = "", y = "Final energy demand road [EJ]")+
    facet_grid(year~region, scales = "free")+
    scale_fill_manual(values = cols)+
    theme_minimal()+
    theme(axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8),
          axis.text.x = element_text(angle = 90, hjust = 1))

        p4 = ggplot()+
    geom_bar(data = totdem1[year %in% c(2005, 2010, 2015) & flow !="ROAD"], aes(x=model, y=value, group = interaction(model, flow), fill = flow), color="black", position="stack", stat = "identity", width = 0.5)+
    labs(x = "", y = "Final energy demand no road [EJ]")+
    facet_grid(year~region, scales = "free")+
    scale_fill_manual(values = cols)+
    theme_minimal()+
    theme(axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8),
          axis.text.x = element_text(angle = 90, hjust = 1))



  return(list(p1,p2,p3,p4))

}


demandEJ_IEAcomp(demand_ej, IEA)
```

# share of alternative techs in ES demand (global values)

```{r, echo=FALSE, warning=FALSE, message=FALSE}
shareAltTechplotf = function(demandkm){
  ## REMIND-EDGE results
  demandkm<- demandkm[,c("subsector_L1","technology", "year","demand_F")]
  demandkm = demandkm[subsector_L1 %in% c("trn_pass_road_LDV_4W", "trn_freight_road_tmp_subsector_L1") & year >= 2010]
  demandkm[, aggr_mode := "LDV"]
  demandkm[subsector_L1 == "trn_freight_road_tmp_subsector_L1", aggr_mode := "Truck"]
  demandkm[, technology := ifelse(technology %in% c("BEV", "Electric", "FCEV", "Hybrid Electric"), "Alternative", "Conventional")]
  demandkm = demandkm[,.(demand_F = sum(demand_F)), by = c("year", "aggr_mode", "technology")]

  demandkm= demandkm[, share := demand_F/sum(demand_F), by = c("year", "aggr_mode")]

  demandkm[, aggr_mode := factor(aggr_mode, levels = c("LDV","Truck"))]

  p = ggplot()+
    geom_line(data = demandkm[technology == "Alternative"], aes(x=year, y=share, color = aggr_mode))+
    labs(x = "", y = "Share [%] on km traveled")+
    facet_wrap(~aggr_mode)+
    theme_minimal()+
    scale_fill_manual(values = cols)+
    # scale_fill_manual("Vehicle Type",values = cols, breaks=legend_ord)+
    theme(axis.text.x = element_text(size = 7),
          axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8))



  plots = list(p=p)
  return(plots)

}

## share of alternative veh on energy services demand
shareAltTechplotf(demand_km)
```

# Energy services demand

```{r, echo=FALSE, warning=FALSE, message=FALSE}
demandkmplotf = function(demandkm, POP){
  ## REMIND-EDGE results
  demandkm<- demandkm[,c("sector","subsector_L3","subsector_L2",
                         "subsector_L1","vehicle_type","technology", "region","year","demand_F")]
  demandkm[,demand_F:=demand_F   ## in millionkm
           *1e-6                      ## in trillion km
           ]
  ## attribute aggregated mode and vehicle names for plotting purposes, and aggregate
  demandkm[, aggr_mode := ifelse(subsector_L1 %in% c("Three-Wheeler", "trn_pass_road_LDV_4W"), "LDV", NA)]
  demandkm[, aggr_mode := ifelse(sector %in% c("trn_freight", "trn_shipping_intl"), "Freight", aggr_mode)]
  demandkm[, aggr_mode := ifelse(sector %in% c("trn_aviation_intl"), "Pass. non LDV", aggr_mode)]
  demandkm[, aggr_mode := ifelse(subsector_L2 %in% c("trn_pass_road_bus", "HSR_tmp_subsector_L2", "Passenger Rail_tmp_subsector_L2", "Cycle_tmp_subsector_L2", "Walk_tmp_subsector_L2", "Domestic Aviation_tmp_subsector_L2", "Bus") | subsector_L1 %in% c("trn_pass_road_LDV_2W"), "Pass. non LDV", aggr_mode)]

  demandkm[, veh := ifelse(grepl("Truck", vehicle_type) & vehicle_type != "Light Truck and SUV" | vehicle_type == "3W Rural", "Truck", NA)]
  demandkm[, veh := ifelse(grepl("Large|SUV|Midsize|Multipurpose Vehicle|Van|Light Truck and SUV", vehicle_type), "Large Cars", veh)]
  demandkm[, veh := ifelse(grepl("Subcompact|Compact|Mini", vehicle_type), "Small Cars", veh)]
  demandkm[, veh := ifelse(grepl("Motorcycle|Moped|Scooter", vehicle_type), "Motorbikes", veh)]
  demandkm[, veh := ifelse(grepl("bus|Bus", vehicle_type), "Bus", veh)]
  demandkm[, veh := ifelse(subsector_L3 == "Domestic Aviation", "Domestic Aviation", veh)]
  demandkm[, veh := ifelse(subsector_L3 == "International Aviation", "International Aviation", veh)]
  demandkm[, veh := ifelse(subsector_L3 == "Domestic Ship", "Domestic Shipping", veh)]
  demandkm[, veh := ifelse(subsector_L3 == "International Ship", "International Shipping", veh)]
  demandkm[, veh := ifelse(grepl("Freight Rail", vehicle_type), "Freight Rail", veh)]
  demandkm[, veh := ifelse(grepl("Passenger Rail|HSR", vehicle_type), "Passenger Rail", veh)]
  demandkm[, veh := ifelse(grepl("Ship", vehicle_type), "Shipping", veh)]
  demandkm[, veh := ifelse(grepl("Cycle|Walk", subsector_L3), "Non motorized", veh)]
  demandkm = demandkm[,.(demand_F = sum(demand_F)), by = c("region", "year", "aggr_mode", "veh")]
  setnames(demandkm, old = "veh", new = "vehicle_type")

  demandkm= demandkm[,.(demand_F = sum(demand_F)), by = c("region", "year", "aggr_mode", "vehicle_type")]

  demandkm[, vehicle_type_plot := factor(vehicle_type, levels = c("LDV","Truck",
                                                                  "Freight Rail",
                                                                  "Motorbikes", "Small Cars", "Large Cars", "Van",
                                                                  "Domestic Aviation", "International Aviation","Bus", "Passenger Rail",
                                                                  "Freight", "Non motorized", "Shipping"))]


  demandkm[, mode := ifelse(vehicle_type %in% c("Freight", "Freight Rail", "Truck", "Shipping"),"freight", "pass")]

  demandkm= demandkm[, .(demand_F = sum(demand_F)), by = c("region", "year", "vehicle_type_plot", "aggr_mode", "mode")]
  demandkmglob = demandkm[,.(demand_F = sum(demand_F)), by = .(year, vehicle_type_plot, aggr_mode, mode)][, region:= "World"]

  demandkm = rbind(demandkmglob,demandkm)
  ## calculate per capita demand
  POP = POP[, .(pop = sum(value)), by = c("region", "year")]
  demandkmcap = merge(demandkm[region!="World"], POP, all.x = TRUE, by =c("year", "region"))

  demandkmcapglob = demandkmcap[,.(demand_F = sum(demand_F), pop = sum(pop)), by = .(year, vehicle_type_plot, aggr_mode, mode)][, region:= "World"]

  demandkmcap = rbind(demandkmcap, demandkmcapglob)
  ## calculate per capita values
  demandkmcap = demandkmcap[order(aggr_mode)]
  demandkmcap[, cap_dem := demand_F*    ## in trillion km
                1e+6/        ## in million km
                pop]         ## in million km/million people=pkm/person


  demandkm = demandkm[order(aggr_mode)]

  ptot_pass = ggplot()+
    geom_area(data = demandkm[mode =="pass"& year > 1980], aes(x=year, y=demand_F, group = interaction(vehicle_type_plot,aggr_mode), fill = vehicle_type_plot), color="black",position= position_stack())+
    labs(x = "", y = "Energy Services demand [trillion pkm]")+
    facet_wrap(~region, nrow = 4, scales = "free")+
    theme_minimal()+
    scale_fill_manual(values = cols)+
    # scale_fill_manual("Vehicle Type",values = cols, breaks=legend_ord)+
    theme(axis.text.x = element_text(size = 7),
          axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8))

  ptot_freight = ggplot()+
    geom_area(data = demandkm[mode =="freight"& year > 2010], aes(x=year, y=demand_F, group = interaction(vehicle_type_plot,aggr_mode), fill = vehicle_type_plot), color="black",position= position_stack())+
    labs(x = "", y = "Energy Services demand [trillion pkm]")+
    facet_wrap(~region, nrow = 4, scales = "free")+
    theme_minimal()+
    scale_fill_manual(values = cols)+
    # scale_fill_manual("Vehicle Type",values = cols, breaks=legend_ord)+
    theme(axis.text.x = element_text(size = 7),
          axis.text.y = element_text(size=7),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size=8))


  pcap_freight = ggplot()+
    geom_area(data = demandkmcap[mode == "freight" & year >= 2020], aes(x=year, y=cap_dem, group = vehicle_type_plot, fill = vehicle_type_plot), color="black",position= position_stack())+
    labs(x = "", y = "Energy Services demand [tkm/cap]")+
    theme_minimal()+
    facet_wrap(~region, nrow = 4, scales = "free")+
    scale_fill_manual("Vehicle Type", values = cols)+
    #expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020,2030,2050, 2100))+
    theme(axis.text.x = element_text(angle = 90,  size = 8, vjust=0.5, hjust=1),
          axis.text.y = element_text(size = 8),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size = 8),
          strip.background = element_rect(color = "grey"),
          axis.line = element_line(size = 0.5, colour = "grey"))

  pcap_pass = ggplot()+
    geom_area(data = demandkmcap[mode == "pass" & year >= 2020], aes(x=year, y=cap_dem, group = vehicle_type_plot, fill = vehicle_type_plot), color="black",position= position_stack())+
    labs(x = "", y = "Energy Services demand [pkm/cap]")+
    theme_minimal()+
    facet_wrap(~region, nrow = 4, scales = "free")+
    scale_fill_manual("Vehicle Type",values = cols)+
    #expand_limits(y = c(0,1))+
    scale_x_continuous(breaks = c(2020, 2030, 2050, 2100))+
    theme(axis.text.x = element_text(angle = 90,  size = 8, vjust=0.5, hjust=1),
          axis.text.y = element_text(size = 8),
          axis.title = element_text(size = 8),
          title = element_text(size = 8),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          strip.text = element_text(size = 8),
          strip.background = element_rect(color = "grey"),
          axis.line = element_line(size = 0.5, colour = "grey"))





  plots = list(ptot_pass = ptot_pass, ptot_freight = ptot_freight, pcap_pass = pcap_pass, pcap_freight = pcap_freight)
  return(plots)

}

## energy services demand
demandkmplotf(demand_km, POP)
```


# LDVs vintages

```{r, echo=FALSE, warning=FALSE, message=FALSE}

plotVint = function(vintcomp, newcomp, sharesVS1, loadFactor){
  vintcomp = vintcomp[,.(totdem, region, subsector_L1, year, technology,vehicle_type, sector, sharetech_vint)]
  newcomp = newcomp[,.(region, subsector_L1, year, technology,vehicle_type, sector, sharetech_new)]

  allfleet = merge(newcomp, vintcomp, all =TRUE, by = c("region", "sector", "subsector_L1", "vehicle_type", "technology",  "year"))
  allfleet = allfleet[sector=="trn_pass"]
  allfleet = merge(allfleet, sharesVS1[,.(shareVS1 = share, region, year, vehicle_type, subsector_L1)], all.x=TRUE, by = c("region", "year", "vehicle_type", "subsector_L1"))
  allfleet[,vintdem:=totdem*sharetech_vint*shareVS1]
  allfleet[,newdem:=totdem*sharetech_new*shareVS1]
  allfleet=melt(allfleet, id.vars = c("region", "sector", "subsector_L1", "vehicle_type", "technology",
                                      "year"), measure.vars = c("vintdem", "newdem"))
  allfleet[,alpha:=ifelse(variable == "vintdem", 0, 1)]

  annual_mileage = 13000
  allfleet = merge(allfleet, loadFactor, by = c("region", "year", "sector", "subsector_L1", "vehicle_type", "technology"))
  allfleet = allfleet[,.(value = sum(value/loadFactor/annual_mileage)), by = c("region", "technology", "variable", "year")]
  allfleet = allfleet[,.(value = sum(value)), by = c("region", "technology", "variable", "year")]
  allfleet[,alphaval := ifelse(variable =="vintdem", 1,0)]

  allfleet_glob = allfleet[,.(value = sum(value)), by = c("technology", "variable", "year", "alphaval")][, region:= "World"]

  allfleet = rbind(allfleet, allfleet_glob)

  p = ggplot()+
  geom_bar(data = allfleet[year %in% c(2015, 2030, 2050, 2100)],
  aes(x=as.character(year),y=value, group=interaction(variable, technology),
  fill = technology), alpha = 0.5, position="stack", stat = "identity", width = 0.5)+
  geom_bar(data = allfleet[year %in% c(2015, 2030, 2050, 2100)],
  aes(x=as.character(year),y=value, group=interaction(variable, technology),
  fill = technology, alpha = factor(alphaval)), position="stack", stat = "identity", width = 0.5, color = "black", size = 0.05)+
  guides(fill = guide_legend(reverse=TRUE))+
  theme_minimal()+
    facet_wrap(~region, nrow = 4,scales = "free")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text = element_text(size=7),
        title = element_text(size=8),
        legend.text = element_text(size=8))+
      scale_x_discrete(breaks = c(2015, 2030, 2050, 2100))+
  scale_alpha_discrete(breaks = c(1,0), name = "Status", labels = c("Vintages","New additions")) +
  guides(linetype=FALSE,
         fill=guide_legend(reverse=FALSE, title="Transport mode"))+
  scale_fill_manual(values = cols)+
  labs(y = "LDV fleet [million Veh]", x="")

  return(p)
  }


p = plotVint(vintcomp, newcomp, sharesVS1 = shares$VS1_shares, loadFactor)

p

```

# Energy intensity for selected LDVs

```{r, echo=FALSE, warning=FALSE}

plotEnInt = function(mj_km, vt){

  p=ggplot()+
    geom_line(data = mj_km[subsector_L1 == "trn_pass_road_LDV_4W" & vehicle_type == vt & year<=2100 & year>=2010], aes(x = as.character(year), y = MJ_km, group = technology, color = technology), size = 1)+
    facet_grid(~region, scales = "free")+
    theme_minimal()+
    expand_limits(y = c(0,0.8))+
    scale_x_discrete(breaks = c(2015,2050,2100))+
    theme(axis.text.x = element_text(angle = 90, vjust = +0.1),
          strip.background = element_rect(color = "grey"))+
    scale_color_manual(values = cols)+
    labs(x = "", y = "Energy intensity [MJ/km]", title = paste0("Example of ", vt))
  return(p)
}

plotEnInt(mj_km = mj_km_data, vt = "Large Car and SUV")
plotEnInt(mj_km = mj_km_data, vt = "Midsize Car")
plotEnInt(mj_km = mj_km_data, vt = "Subcompact Car")
```
